#!/usr/bin/env python3
"""docmap.py -- generate docs/DOC_MAP.md: the map of the MAPS.

WHY THIS EXISTS (a Rule-0 failure, kept loud). The tree grew FIVE documentation generators -- docgen.py
(REFERENCE.md, every module), capdoc.py (CAPABILITIES.md, the job-oriented catalog view), apiquickref.py
(API_QUICKREF.md, the curated app-building surface), facultymap.py (docs/FACULTY_MAP.md, the mind's methods by
topic), and holographic_skills.manifest() (the machine-readable card set) -- and NOTHING listed them in one
place. Root scripts are not catalog capabilities, so `find_capability` cannot surface them: an organization
audit in July 2026 rebuilt a per-symbol index without finding apiquickref.py first, and only a docstring
cross-reference caught it. The fix is this page (one table: which doc answers which question, and how to
regenerate it) plus a catalog entry pointing here, so the doc surface is discoverable the same way the engine
surface is.

Also emits two SMALL mermaid diagrams (GitHub renders ```mermaid natively -- no dependency enters the engine):
the family layout and the doc-generation pipeline. KEPT NEGATIVE: a full 502-module import graph was considered
and rejected -- at that scale a diagram is a hairball, not a map; the family level (10 nodes) is where a picture
still beats a table.

Run:  python3 docmap.py          Output: docs/DOC_MAP.md
"""
import glob
import os

REPO = os.path.dirname(os.path.abspath(__file__))

# The rows are maintained HERE, next to the generators they describe, so adding a generator without adding its
# row is visible in the same review. (question, doc, generator, scope)
DOCS = [
    ("Read the WHOLE engine, module by module", "REFERENCE.md", "docgen.py",
     "every holographic_* module: its why-docstring, public classes and functions"),
    ("I have a JOB to do -- which capability, and what do I type?", "CAPABILITIES.md", "capdoc.py",
     "the curated capability catalog, grouped, with runnable examples (machine twin: capabilities.json)"),
    ("What can the APP-BUILDING surface do (scene, mesh, camera, render)?", "API_QUICKREF.md", "apiquickref.py",
     "one line per public symbol of a short curated module list"),
    ("What can the MIND do, by topic (mesh_*, render_*, file_* ...)?", "docs/FACULTY_MAP.md", "facultymap.py",
     "all UnifiedMind public methods, prefix-clustered, one-line docs (live introspection)"),
    ("Machine-readable cards for agents (act/choose routing, autocomplete)", "(in-memory)",
     "holographic_skills.manifest()", "capability + method cards as data; not a file on disk"),
    ("Is the tree still ORGANIZED (misc budget, giants, section markers)?", "(report)",
     "tools/structure_audit.py", "budgeted-baseline structural gates; fails only on regression"),
]


def family_counts():
    fam = {}
    for p in glob.glob(os.path.join(REPO, "holographic", "*", "holographic_*.py")):
        fam.setdefault(p.split(os.sep)[-2], 0)
        fam[p.split(os.sep)[-2]] += 1
    return dict(sorted(fam.items(), key=lambda kv: -kv[1]))


def main():
    fam = family_counts()
    lines = []
    lines.append("# Documentation map -- which doc answers which question")
    lines.append("")
    lines.append("*Generated by `docmap.py`; regenerate it whenever a doc generator is added. This page exists because "
                 "the doc generators themselves were once undiscoverable (see the script's docstring).*")
    lines.append("")
    lines.append("| The question you have | Open / run | Generator | Scope |")
    lines.append("|---|---|---|---|")
    for q, doc, gen, scope in DOCS:
        lines.append("| %s | `%s` | `%s` | %s |" % (q, doc, gen, scope))
    lines.append("")
    lines.append("Regenerate the generated set in one go (the close-out ritual):")
    lines.append("")
    lines.append("```sh")
    lines.append("python3 capdoc.py && python3 docgen.py && python3 apiquickref.py && python3 facultymap.py && python3 docmap.py")
    lines.append("```")
    lines.append("")
    lines.append("## Family layout (%d modules)" % sum(fam.values()))
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph LR")
    lines.append("    H[holographic/]")
    for k, n in fam.items():
        if k.startswith("__"):
            continue
        lines.append("    H --> %s[\"%s (%d)\"]" % (k[:4], k, n))
    lines.append("```")
    lines.append("")
    lines.append("## Doc pipeline")
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph LR")
    lines.append("    SRC[\"module docstrings + code\"] --> DG[docgen.py] --> REF[REFERENCE.md]")
    lines.append("    CAT[\"capability catalog\"] --> CD[capdoc.py] --> CAP[\"CAPABILITIES.md + capabilities.json\"]")
    lines.append("    SRC --> AQ[apiquickref.py] --> QR[API_QUICKREF.md]")
    lines.append("    MIND[\"UnifiedMind introspection\"] --> FM[facultymap.py] --> FMAP[docs/FACULTY_MAP.md]")
    lines.append("    MIND --> SK[\"skills.manifest()\"]")
    lines.append("```")
    lines.append("")
    out = os.path.join(REPO, "docs", "DOC_MAP.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote %s -- %d docs mapped, %d families diagrammed" % (out, len(DOCS), len(fam)))


if __name__ == "__main__":
    main()
