"""Regenerate docs/FACULTY_MAP.md -- the TOPICAL index of every public UnifiedMind method.

WHY this exists: unified.py is one 14,000+ line class with 1,270+ methods whose internal ordering follows the
SHIPPING ARCS (each build landed at an insertion anchor), not the topics -- so a person asking "what can the mind
do with meshes?" has no page to open. find_capability answers that for machines; this map answers it for humans.
It is GENERATED from live introspection (method names + first docstring lines), the same sources seed_from_mind
harvests, so it can never drift from the code the way a hand-written index would -- regenerate it in close-out
right next to capdoc.py / docgen.py.

Grouping is by the method name's first token (mesh_, render_, file_, sdf_ ...): measured on the live mind this
yields ~116 clusters of >=3 methods covering the majority of the surface, with the rest in an alphabetical tail.
That convention is already how the surface is NAMED -- the map just makes the existing organization visible.

Run:  python3 facultymap.py
"""
import inspect
import os
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, REPO)

MIN_CLUSTER = 3   # a prefix with fewer members isn't a topic, it's a coincidence; those go to the tail


def one_liner(fn):
    """The first docstring line, trimmed -- the same summary seed_from_mind puts in the catalog."""
    doc = (inspect.getdoc(fn) or "").strip().split("\n")[0]
    return doc[:150] if doc else "(no docstring)"


def main():
    import lecore
    m = lecore.UnifiedMind(dim=64, seed=0)
    kind = type(m)
    meths = sorted(n for n in dir(m) if not n.startswith("_") and callable(getattr(kind, n, None)))

    groups = {}
    for n in meths:
        groups.setdefault(n.split("_")[0], []).append(n)
    clusters = {k: v for k, v in groups.items() if len(v) >= MIN_CLUSTER}
    tail = sorted(n for k, v in groups.items() if len(v) < MIN_CLUSTER for n in v)

    lines = []
    lines.append("# Faculty map -- UnifiedMind's %d public methods, by topic" % len(meths))
    lines.append("")
    lines.append("*Generated by `facultymap.py` from live introspection -- do not edit by hand; regenerate instead.*")
    lines.append("*%d topical clusters (prefix, >= %d methods) + an alphabetical tail of %d.*"
                 % (len(clusters), MIN_CLUSTER, len(tail)))
    lines.append("")
    lines.append("## Topics")
    lines.append("")
    for k in sorted(clusters):
        lines.append("- [%s](#%s) (%d)" % (k, k, len(clusters[k])))
    lines.append("")
    for k in sorted(clusters):
        lines.append("## %s" % k)
        lines.append("")
        for n in sorted(clusters[k]):
            lines.append("- **`%s`** -- %s" % (n, one_liner(getattr(kind, n))))
        lines.append("")
    lines.append("## everything else (alphabetical)")
    lines.append("")
    for n in tail:
        lines.append("- **`%s`** -- %s" % (n, one_liner(getattr(kind, n))))
    lines.append("")

    out = os.path.join(REPO, "docs", "FACULTY_MAP.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote %s -- %d methods, %d clusters, %d in tail" % (out, len(meths), len(clusters), len(tail)))


if __name__ == "__main__":
    main()
