"""Bake a scene SDF into a grid once, then sample it O(1) -- the realtime renderer's distance-field shortcut.

Profiling the shader showed the cost is dominated by SDF evaluation: a trace spends ~96 steps per pixel, each step
evaluating the analytic union, and that union is O(number of primitives) per point (a min over every primitive) -- and
the SAME eval is paid again for shadows, ambient occlusion, reflections, and normals, and again by navigation,
collision, and emission. So the SDF eval is the whole system's shared bottleneck, and it gets WORSE as a scene gains
objects.

The shortcut every realtime renderer takes (Unreal's Global Distance Fields, Redshift, mesh SDFs): PRECOMPUTE the
signed distance on a 3-D grid once, then TRILINEARLY sample it. A sample is O(1) regardless of how many primitives the
scene has -- a 100-object scene traces as fast as a 1-object scene. `GridSDF` is a drop-in for the analytic union (it
exposes `.eval` and `.ids`), so the shader, the ray-marcher, the navigator, the collider, and the emitter all get the
speedup for free, from one bake.

HONEST TRADE (kept loud): the grid is APPROXIMATE -- surface detail below the cell size is lost, so thin features blur
at low resolution; and outside the grid box the exact box distance is returned (conservative, so tracing never
overshoots into the volume). The bake has an up-front cost that pays off once enough rays/frames reuse it -- which is
the whole point of a cache. Deterministic; NumPy only.
"""
import numpy as np


def bake_sdf_grid(sdf_eval, lo, hi, res, ids_fn=None):
    """Sample `sdf_eval` (a callable P (M,3)->distance) on a `res`-per-axis grid spanning [lo, hi]. Returns
    (dist_grid (rx,ry,rz), ids_grid or None). `ids_fn` (callable P->int primitive index) bakes a nearest-primitive
    id grid for per-object colour. This is the one precompute; everything downstream samples the result. The
    position grid is generated by the Cache home (consolidation H2) -- bit-identical to the inline meshgrid."""
    from holographic_cachehome import Cache
    lo = np.asarray(lo, float); hi = np.asarray(hi, float)
    pts, r = Cache.grid_points(lo, hi, res)                          # the shared position-grid generator
    shape = tuple(int(x) for x in r)
    dist = np.asarray(sdf_eval(pts), float).reshape(shape)
    ids = None
    if ids_fn is not None:
        ids = np.asarray(ids_fn(pts), int).reshape(shape)
    return dist, ids


class GridSDF:
    """A baked distance field that stands in for the analytic union: `.eval(P)` trilinearly samples the grid (O(1) per
    point, independent of scene complexity), `.ids(P)` reads the nearest-primitive id (nearest-cell). Build it with
    `GridSDF.bake(union, lo, hi, res)`."""

    def __init__(self, dist, lo, hi, ids=None):
        self.dist = np.asarray(dist, float)
        self.lo = np.asarray(lo, float)
        self.hi = np.asarray(hi, float)
        self.res = np.array(self.dist.shape)
        self.ids_grid = None if ids is None else np.asarray(ids, int)
        self._cell = (self.hi - self.lo) / np.maximum(self.res - 1, 1)

    @classmethod
    def bake(cls, union, lo, hi, res):
        """Bake an analytic union (anything with `.eval`, and optionally `.ids`) into a GridSDF."""
        ids_fn = getattr(union, "ids", None)
        dist, ids = bake_sdf_grid(union.eval, lo, hi, res, ids_fn=ids_fn)
        return cls(dist, lo, hi, ids=ids)

    def _grid_coords(self, P):
        """Continuous grid coordinates of world points, and a mask of which points are inside the grid box."""
        frac = (P - self.lo) / np.maximum(self.hi - self.lo, 1e-12)
        coord = frac * (self.res - 1)
        inside = np.all((P >= self.lo) & (P <= self.hi), axis=1)
        return coord, inside

    def _box_distance(self, P):
        """Exact distance from a point to the grid's axis-aligned box (0 inside) -- the conservative value used
        outside the baked volume so a ray approaches the box correctly without overshooting."""
        q = np.maximum(self.lo - P, P - self.hi)                  # per-axis outside amount
        outside = np.linalg.norm(np.maximum(q, 0.0), axis=1)
        inside = np.minimum(np.max(q, axis=1), 0.0)
        return outside + inside

    def eval(self, P):
        """Trilinearly sample the baked distance at world points P (M,3). Outside the box -> exact box distance."""
        P = np.asarray(P, float)
        coord, inside = self._grid_coords(P)
        c = np.clip(coord, 0, self.res - 1)
        i0 = np.floor(c).astype(int)
        i1 = np.minimum(i0 + 1, self.res - 1)
        f = c - i0
        g = self.dist
        # gather the 8 corners and blend
        x0, y0, z0 = i0[:, 0], i0[:, 1], i0[:, 2]
        x1, y1, z1 = i1[:, 0], i1[:, 1], i1[:, 2]
        fx, fy, fz = f[:, 0], f[:, 1], f[:, 2]
        c00 = g[x0, y0, z0] * (1 - fx) + g[x1, y0, z0] * fx
        c01 = g[x0, y0, z1] * (1 - fx) + g[x1, y0, z1] * fx
        c10 = g[x0, y1, z0] * (1 - fx) + g[x1, y1, z0] * fx
        c11 = g[x0, y1, z1] * (1 - fx) + g[x1, y1, z1] * fx
        c0 = c00 * (1 - fy) + c10 * fy
        c1 = c01 * (1 - fy) + c11 * fy
        val = c0 * (1 - fz) + c1 * fz
        out = self._box_distance(P)                                # conservative outside the volume
        return np.where(inside, val, np.maximum(val, out))

    def ids(self, P):
        """Nearest-primitive id at world points (for per-object colour). Falls back to zeros if no id grid was baked."""
        P = np.asarray(P, float)
        if self.ids_grid is None:
            return np.zeros(len(P), int)
        coord, _ = self._grid_coords(P)
        idx = np.clip(np.round(coord).astype(int), 0, self.res - 1)
        return self.ids_grid[idx[:, 0], idx[:, 1], idx[:, 2]]


def _selftest():
    """A baked grid reproduces an analytic sphere's SDF to within the cell size, and evaluating it is O(1) in the
    number of primitives -- a many-primitive union costs the SAME to sample once baked."""
    import time
    sphere = lambda P: np.linalg.norm(P, axis=1) - 1.0
    lo = np.full(3, -2.0); hi = np.full(3, 2.0)
    gs = GridSDF.bake(type("U", (), {"eval": staticmethod(sphere)})(), lo, hi, 64)
    pts = np.random.default_rng(0).uniform(-1.8, 1.8, size=(5000, 3))
    err = np.abs(gs.eval(pts) - sphere(pts)).max()
    cell = (hi - lo).max() / 63
    assert err < 3 * cell                                          # accurate to ~a cell
    # O(1) in primitive count: a union of 50 spheres, baked, samples in ~the same time as 1
    class Union:
        def __init__(s, n): s.cs = np.random.default_rng(1).uniform(-1, 1, (n, 3))
        def eval(s, P):
            return np.min(np.stack([np.linalg.norm(P - c, axis=1) - 0.4 for c in s.cs]), axis=0)
    big = Union(50); gbig = GridSDF.bake(big, lo, hi, 48)
    q = np.random.default_rng(2).uniform(-1.8, 1.8, (20000, 3))
    t = time.time(); [big.eval(q) for _ in range(5)]; t_analytic = time.time() - t
    t = time.time(); [gbig.eval(q) for _ in range(5)]; t_baked = time.time() - t
    assert t_baked < t_analytic                                    # sampling beats evaluating 50 primitives
    print("sdfbake selftest ok: baked sphere err %.4f (< 3 cells); 50-primitive union %.1fx faster to sample than to evaluate"
          % (err, t_analytic / max(t_baked, 1e-6)))


if __name__ == "__main__":
    _selftest()
