"""holographic_matbake.py -- BAKE VIEW-INDEPENDENT CHANNELS (fluids/matter backlog, performance item MC2).

MC1 compiled a material once and folded its CONSTANT channels, but a procedural channel -- a roughness or colour that
varies with surface position -- still re-evaluates its field at every hit, every frame. MC2 is the next move from the
backlog: BAKE the view-independent parts into a projection and QUERY them. A procedural field sampled over the
object's bounds becomes a grid; per hit you trilinearly LOOK UP the grid (O(1), independent of how hairy the field
was) instead of re-running the noise/pattern. This reuses the exact machinery sdfbake uses to turn an analytic SDF
into a GridSDF -- here pointed at a material channel instead of a distance.

A baked material therefore shades by: fold the constants (MC1) + look up the baked position-dependent channels. What
stays un-baked is the genuinely VIEW-dependent part (specular), which is MC3's (position, view) LUT.

KEPT NEGATIVE (loud): the bake trades MEMORY for speed and introduces INTERPOLATION error -- a grid at resolution R
reproduces a smooth field well but blurs detail finer than a cell (bump the resolution, or keep sharp features
procedural). It pays off in REPEATED sampling (many hits / many frames / relight), not a single evaluation -- the
bake itself costs one full grid evaluation up front. Only VIEW-INDEPENDENT channels bake here. Deterministic.
"""
import numpy as np

from holographic_matcompile import CHANNELS, _is_const, _resolve
from holographic_compile import DEFAULT_CACHE


class BakedField:
    """A field sampled onto a regular 3-D grid, read back by trilinear interpolation -- O(1) per point, independent
    of how expensive the original field was. Holds a scalar grid (rx,ry,rz) or a colour grid (rx,ry,rz,3)."""

    def __init__(self, grid, lo, hi):
        self.grid = np.asarray(grid, float)
        self.lo = np.asarray(lo, float)
        self.hi = np.asarray(hi, float)
        self.res = np.array(self.grid.shape[:3])
        self.channels = self.grid.shape[3] if self.grid.ndim == 4 else 0

    def sample(self, P):
        """Trilinearly sample the grid at world points P (M,3). Points outside the box clamp to the nearest edge."""
        P = np.asarray(P, float)
        frac = (P - self.lo) / np.maximum(self.hi - self.lo, 1e-12)
        coord = np.clip(frac * (self.res - 1), 0.0, self.res - 1)          # continuous grid coords, clamped in-box
        i0 = np.floor(coord).astype(int)
        i1 = np.minimum(i0 + 1, self.res - 1)
        w = coord - i0                                                     # per-axis interpolation weight in [0,1]
        out = None
        for dx in (0, 1):                                                  # accumulate over the 8 surrounding corners
            for dy in (0, 1):
                for dz in (0, 1):
                    wx = w[:, 0] if dx else 1.0 - w[:, 0]
                    wy = w[:, 1] if dy else 1.0 - w[:, 1]
                    wz = w[:, 2] if dz else 1.0 - w[:, 2]
                    ix = i1[:, 0] if dx else i0[:, 0]
                    iy = i1[:, 1] if dy else i0[:, 1]
                    iz = i1[:, 2] if dz else i0[:, 2]
                    corner = self.grid[ix, iy, iz]                        # (M,) scalar or (M,3) colour
                    wgt = wx * wy * wz
                    contrib = wgt[:, None] * corner if corner.ndim > 1 else wgt * corner
                    out = contrib if out is None else out + contrib
        return out


def bake_field(field_fn, name, lo, hi, res=24):
    """Sample a material channel field over [lo,hi] on a res^3 grid -> a BakedField. `name`='color' bakes an
    (rx,ry,rz,3) colour grid; any other channel bakes an (rx,ry,rz) scalar grid. This is the ONE precompute. The
    position grid is generated by the Cache home (consolidation H2) -- bit-identical to the inline meshgrid."""
    from holographic_cachehome import Cache
    lo = np.asarray(lo, float); hi = np.asarray(hi, float)
    pts, _ = Cache.grid_points(lo, hi, res)                               # the shared position-grid generator
    vals = _resolve(name, field_fn, pts, len(pts))                        # evaluate the field once, everywhere
    if name == "color":
        grid = vals.reshape(res, res, res, 3)
    else:
        grid = vals.reshape(res, res, res)
    return BakedField(grid, lo, hi)


def bake_material(material, lo, hi, res=24):
    """Bake a material into a fast shader: CONSTANT channels folded (MC1), VIEW-INDEPENDENT socket channels baked to
    BakedField lookups (MC2). Returns a shade(points)->channel-dict that is all folds + trilinear lookups -- no
    per-hit field evaluation. `lo,hi` are the object bounds the fields are baked over."""
    const_vals = {}
    baked = {}
    for name in CHANNELS:
        ch = getattr(material, name)
        if _is_const(name, ch):
            const_vals[name] = _resolve(name, ch, np.zeros((2, 3)), 2)[0]   # fold the constant (MC1)
        else:
            baked[name] = bake_field(ch, name, lo, hi, res=res)            # bake the position-dependent field (MC2)

    def shade(points):
        points = np.asarray(points, float)
        n = len(points)
        out = {}
        for name in CHANNELS:
            if name in const_vals:
                cv = const_vals[name]
                out[name] = np.tile(cv, (n, 1)) if np.ndim(cv) and np.size(cv) == 3 else np.full(n, float(cv))
            else:
                out[name] = baked[name].sample(points)                    # O(1) trilinear lookup, no field eval
        return out

    shade.const_names = list(const_vals)
    shade.baked_names = list(baked)
    return shade


def _selftest():
    """Bake a procedural roughness+colour material over a box, and confirm the baked lookup matches the procedural
    evaluation within interpolation error, that only view-independent sockets baked, and that a finer grid is more
    accurate (the resolution/accuracy trade)."""
    from holographic_surface import SurfaceMaterial
    from holographic_param import Param

    # a smooth procedural roughness (varies with x) and a smooth colour ramp (varies with y)
    rough = lambda P, **k: 0.3 + 0.2 * np.sin(np.asarray(P)[:, 0] * 2.0)
    col = lambda P, **k: np.stack([0.5 + 0.4 * np.asarray(P)[:, 1],
                                   np.full(len(P), 0.3),
                                   np.full(len(P), 0.6)], axis=1)
    mat = SurfaceMaterial(color=Param(field=col), roughness=Param(field=rough), reflect=0.1, emission=0.0)

    lo, hi = (-1.0, -1.0, -1.0), (1.0, 1.0, 1.0)
    pts = np.random.default_rng(0).uniform(-0.9, 0.9, size=(200, 3))       # inside the baked box

    shade = bake_material(mat, lo, hi, res=48)
    ref = mat.resolve(pts)
    got = shade(pts)

    # baked lookups match the procedural evaluation within interpolation error
    assert np.abs(got["roughness"] - ref["roughness"]).max() < 0.02, np.abs(got["roughness"] - ref["roughness"]).max()
    assert np.abs(got["color"] - ref["color"]).max() < 0.02
    # constants folded, procedural channels baked
    assert set(shade.const_names) == {"reflect", "emission", "opacity"}
    assert set(shade.baked_names) == {"color", "roughness"}

    # the resolution/accuracy trade: a finer grid is closer to the true field
    coarse = bake_material(mat, lo, hi, res=8)(pts)
    fine = bake_material(mat, lo, hi, res=64)(pts)
    err_coarse = np.abs(coarse["roughness"] - ref["roughness"]).max()
    err_fine = np.abs(fine["roughness"] - ref["roughness"]).max()
    assert err_fine < err_coarse, (err_coarse, err_fine)

    print("holographic_matbake selftest OK: a procedural roughness+colour material baked over a box -- per-hit "
          "shading is now a trilinear LOOKUP matching the procedural eval to <0.02 (res 48); constants folded, "
          "position-dependent channels baked; finer grid is more accurate (err %.4f @res8 -> %.4f @res64) -- the "
          "memory/accuracy trade, kept honest" % (err_coarse, err_fine))


if __name__ == "__main__":
    _selftest()
