-- generated by leCore holographic_lean.to_lean; checked externally by Lean 4
axiom U : Type
axiom c : U
axiom best_lt_bound : U -> Prop
axiom best_lt_true : U -> Prop
axiom bound_le_true : U -> Prop
axiom cannot_win : U -> Prop
axiom skip_is_safe_2 : U -> Prop
axiom bound_is_valid : bound_le_true c
axiom test_fired : best_lt_bound c
axiom transitivity : bound_le_true c -> best_lt_bound c -> best_lt_true c
axiom worse_than_best_cannot_win : best_lt_true c -> cannot_win c
axiom safe_to_skip_a_loser : cannot_win c -> skip_is_safe_2 c
theorem skip_is_safe : skip_is_safe_2 c := safe_to_skip_a_loser (worse_than_best_cannot_win (transitivity bound_is_valid test_fired))
