"""Emit pages/zeroasset_three.html -- a three.js scene with ZERO downloaded scene data.

THE CLAIM, AND IT IS A BYTE COUNT. Sixteen of three.js's own examples exist to make assets smaller
or arrive sooner: Draco, KTX2, meshopt, 3D tiles, progressive LOD. Their whole subject is MOVING
BYTES. leCore's core trick is that content is a FUNCTION OF ITS NAME -- the search page ships a
6,767-term vocabulary as zero bytes, and the field demo invents a wave for a word that has never
existed. Point that at a scene and the geometry, the placement, the materials and the variation all
stop being data.

WHAT IS ACTUALLY SHIPPED: the name of the district, as a string. Everything else -- every tower's
position, height, width, rotation, colour and the coherent skyline they form -- is recomputed in the
browser from that name, bit-identically on every machine, using the ENGINE'S hash.

THE BASELINE IS THE STRONGEST HONEST ONE, not a strawman. A glTF using EXT_mesh_gpu_instancing (the
best case: one base mesh, per-instance TRS) still carries translation+rotation+scale+colour per
instance. That is what the page counts against, not an uninstanced dump.

THE SKYLINE IS A SUM OF PLANE WAVES, which is the point rather than decoration: white noise would
give a field of unrelated towers. Fractional-power encoding gives COHERENT STRUCTURE -- a dense
centre, thinning outskirts, ridges and squares -- from the same hash, which is exactly what the
field demo showed in 2D.
"""
import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.abspath(__file__))
while ROOT != os.path.dirname(ROOT) and not os.path.exists(os.path.join(ROOT, "lecore.py")):
    ROOT = os.path.dirname(ROOT)
assert os.path.exists(os.path.join(ROOT, "lecore.py")), "repo root not found"
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import lecore  # noqa: E402
import holographic.agents_and_reasoning.holographic_hashatom as HA  # noqa: E402
import holographic.misc.holographic_determinism as DT  # noqa: E402

N_TOWERS = 24000
N_WAVES = 12


def fnv1a(s):
    return int(HA.fnv1a(s))


def pcg(v):
    return int(np.asarray(DT.hash32_pcg(np.uint32(v))).item())


def wave_table(name):
    """The district's plane waves. Same construction as the field demo, in 2D, from the name."""
    out = []
    h0 = fnv1a(name)
    for i in range(N_WAVES):
        h = pcg(h0 ^ ((i * 2654435761) & 0xFFFFFFFF))
        out.append(dict(
            fx=((h & 0xFF) / 255 - 0.5) * 0.55,
            fy=(((h >> 8) & 0xFF) / 255 - 0.5) * 0.55,
            ph=((h >> 16) & 0xFFFF) / 65535 * 6.2831853,
            amp=0.35 + ((h >> 28) & 0xF) / 15 * 0.9,
        ))
    return out


def reference(name, k=64):
    """Values the page checks its own arithmetic against. A page that computes its scene from a hash
    must prove its hash is the ENGINE'S hash -- otherwise it is generating a different world that
    merely looks plausible, which is the exact bug that cost a day earlier in this arc."""
    h0 = fnv1a(name)
    return dict(name=name, fnv=h0,
                pcg=[pcg(h0 ^ i) for i in range(k)])


def main(out="pages/zeroasset_three.html"):
    mind = lecore.UnifiedMind(dim=256, seed=0)
    names = ["harbour district", "old town", "spire quarter", "the shallows", "moose country"]
    payload = dict(
        towers=N_TOWERS, waves=N_WAVES,
        tables={n: wave_table(n) for n in names},
        names=names,
        refs={n: reference(n) for n in names},
        # the byte accounting, computed here so the page cannot fudge it
        bytes_per_instance=13 * 4,   # translation 3f + quaternion 4f + scale 3f + colour 3f
        capability=mind.glsl_kernel("hdrift_grad")["does"][:150],
    )
    three = open(os.path.join(ROOT, "pages", "vendor", "three.inline.js"), encoding="utf-8").read()
    html = (TEMPLATE.replace("__THREE__", three)
        .replace("__GEN__", GEN_SHADER.replace("${P_WAVES}", str(N_WAVES)))
        .replace("__DATA__", json.dumps(payload, separators=(",", ":"))))
    p = os.path.join(ROOT, out)
    with open(p, "w", encoding="utf-8") as fh:
        fh.write(html)
    scene_bytes = N_TOWERS * payload["bytes_per_instance"]
    shipped = sum(len(n) for n in names)
    print("wrote %s  %.0f KB" % (out, os.path.getsize(p) / 1024))
    print("  %s towers; a glTF with EXT_mesh_gpu_instancing would carry %.2f MB of instance data"
          % (f"{N_TOWERS:,}", scene_bytes / 1e6))
    print("  this page ships %d bytes of scene data (the district names) -- ratio %.0fx"
          % (shipped, scene_bytes / max(shipped, 1)))
    return p


GEN_SHADER = r'''
// ---- leCORE GLSL: THE SCENE IS GENERATED BY A SHADER --------------------------------------------
// One fragment per instance. It hashes the district name with the instance index, sums the plane
// waves, and writes the instance's transform and colour to two float targets. Nothing is decoded,
// nothing is uploaded per instance, and nothing comes back to the CPU -- the vertex shader below
// reads these textures directly. This is "an atom is a function of its name" as a fragment pass.
const GEN_FS = `// LECORE_GEN_FS
precision highp float; precision highp int;
uniform int uN, uW, uNW;
uniform uint uSeed;
uniform vec4 uWaves[${P_WAVES}];      // fx, fy, phase, amp
layout(location = 0) out vec4 oXform;  // x, y, z, rotY
layout(location = 1) out vec4 oScale;  // w, h, d, unused
layout(location = 2) out vec4 oColor;  // r, g, b, field

// The ENGINE'S hash. A different mixer draws a different city that merely looks plausible.
uint pcg(uint v){
  uint s = v * 747796405u + 2891336453u;
  uint w = ((s >> ((s >> 28u) + 4u)) ^ s) * 277803737u;
  return (w >> 22u) ^ w;
}

void main(){
  int i = int(gl_FragCoord.x) + int(gl_FragCoord.y) * uW;
  if (i >= uN) { oXform = vec4(0.0); oScale = vec4(0.0); oColor = vec4(0.0); return; }
  uint a = pcg(uSeed ^ (uint(i + 1) * 2246822519u));
  uint b = pcg(a ^ 0x9e3779b9u);
  float S = 105.0;
  float x = (float(a & 0xffffu) / 65535.0 - 0.5) * 2.0 * S;
  float z = (float((a >> 16u) & 0xffffu) / 65535.0 - 0.5) * 2.0 * S;
  // the coherent part: a sum of plane waves, which is what makes a skyline instead of a scatter
  float f = 0.0;
  for (int k = 0; k < uNW; ++k) {
    vec4 c = uWaves[k];
    f += c.w * cos(c.x * x + c.y * z + c.z);
  }
  f /= float(uNW);
  float jitter = float(b & 0xffu) / 255.0;
  float h = max(0.6, pow(f * 0.5 + 0.5, 2.6) * 46.0 * (0.55 + 0.9 * jitter));
  float wf = 1.1 + float((b >> 8u) & 0xffu) / 255.0 * 2.4 * (0.5 + 0.5 * (f * 0.5 + 0.5));
  float df = 1.1 + float((b >> 16u) & 0xffu) / 255.0 * 2.4 * (0.5 + 0.5 * (f * 0.5 + 0.5));
  float rot = float((b >> 24u) & 0xffu) / 255.0 * 1.5707963;
  float warm = clamp(f * 0.7 + 0.5, 0.0, 1.0);
  oXform = vec4(x, h * 0.5, z, rot);
  oScale = vec4(wf, h, df, 0.0);
  oColor = vec4(0.10 + 0.62 * warm + 0.10 * jitter,
                0.16 + 0.34 * warm + 0.06 * jitter,
                0.34 - 0.14 * warm + 0.10 * jitter, f);
}`;
'''

TEMPLATE = r"""<!doctype html>
<meta charset="utf-8">
<title>leCore x three.js — a scene with no assets</title>
<style>
 html,body{margin:0;background:#05060a;color:#c9d1e0;font:13px/1.6 ui-monospace,Consolas,monospace}
 .wrap{max-width:1200px;margin:18px auto;padding:0 18px}
 h1{font-size:19px;margin:0 0 4px;font-weight:600;color:#e8eef8}
 p.lede{color:#8891a3;margin:0 0 12px;max-width:980px}
 #cv{width:100%;max-width:1160px;aspect-ratio:16/9;display:block;border-radius:10px;cursor:grab}
 #cv:active{cursor:grabbing}
 .bar{display:flex;gap:20px;align-items:center;flex-wrap:wrap;margin:12px 0}
 .grp{display:flex;gap:8px;align-items:center}
 .lbl{color:#69707f;font-size:12px;letter-spacing:.04em;text-transform:uppercase}
 button{background:#141821;color:#aeb6c6;border:1px solid #262d3b;border-radius:6px;padding:7px 12px;
   cursor:pointer;font:13px ui-monospace,Consolas,monospace}
 button:hover{background:#1b2130;color:#dfe6f2}
 .seg{display:flex;border:1px solid #262d3b;border-radius:6px;overflow:hidden}
 .seg button{border:0;border-radius:0;border-right:1px solid #262d3b}
 .seg button:last-child{border-right:0}
 .seg button.on{background:#2a3a5c;color:#eaf1ff}
 input[type=text]{background:#101319;color:#e6ecf7;border:1px solid #232838;border-radius:6px;
   padding:8px 11px;font:13px ui-monospace,Consolas,monospace;min-width:260px}
 .st{color:#7f8798} .st b{color:#5ad67d;font-weight:600}
 .ok{color:#5ad67d} .bad{color:#ff6b6b} .big{color:#ffd08a;font-weight:600}
 table.acct{border-collapse:collapse;margin:10px 0;font-size:12px}
 table.acct td{border-bottom:1px solid #1c2230;padding:4px 18px 4px 0;color:#8891a3}
 table.acct th{text-align:right;color:#e8eef8;padding:4px 18px 6px 0;border-bottom:1px solid #2a3142}
 table.acct th:first-child{text-align:left}
 table.acct td.v{color:#e8eef8;text-align:right;font-variant-numeric:tabular-nums}
 .note{color:#6f7787;font-size:12px;margin-top:10px;max-width:980px}
</style>
<div class=wrap>
<h1>leCore &times; three.js &mdash; a scene with no assets</h1>
<p class=lede>
Every tower's position, height, width, rotation and colour &mdash; and the coherent skyline they
form &mdash; is recomputed in your browser from <b>the name of the district</b>. Nothing is
downloaded, nothing is stored, and the same name gives the same city on every machine.
<b>Type a name that has never existed.</b>
</p>

<canvas id=cv></canvas>

<div class=bar>
  <div class=grp>
    <span class=lbl>district</span>
    <input id=nm type=text spellcheck=false value="harbour district">
    <button id=go>build it</button>
  </div>
  <div class=grp><span class=lbl>show</span>
    <div class=seg id=viewseg>
      <button data-view=0 class=on>city</button>
      <button data-view=1>field</button>
    </div>
  </div>
  <div class=grp><button id=spin>orbit: on</button></div>
</div>
<div class=bar><span class=st id=st>starting&hellip;</span></div>
<div class=bar><span class=st id=chk></span></div>

<table class=acct id=acct></table>

<p class=note>
<b>Why this is the demo.</b> Sixteen of three.js's own examples exist to make assets smaller or
arrive sooner &mdash; Draco, KTX2, meshopt, 3D tiles, progressive LOD. Their subject is moving
bytes. Here there are no bytes to move: an object is a <i>function of its name</i>, the same trick
that lets leCore ship a 6,767-term vocabulary as zero bytes. The baseline in the table is the
<i>strongest honest one</i> &mdash; a glTF using <code>EXT_mesh_gpu_instancing</code>, which is the
best case for the other side, not an uninstanced dump.
</p>
<p class=note>
<b>The skyline is a sum of plane waves, and that is the point rather than decoration.</b> White
noise from a hash would give a field of unrelated towers. Fractional-power encoding gives coherent
structure &mdash; a dense centre, thinning outskirts, ridges and clearings &mdash; out of the same
hash. It is the field demo's trick in two dimensions, wearing a city.
</p>
</div>

<script>__THREE__</script>
<script>
const P = __DATA__;
const cv = document.getElementById("cv"), st = document.getElementById("st"), chk = document.getElementById("chk");

// ---- the vocabulary is a function --------------------------------------------------------------
// The ENGINE'S hash, not a lookalike. A page that generates its world from a hash must prove the
// hash is the right one, or it is generating a different world that merely looks plausible.
function fnv1a(s){ let h=2166136261>>>0;
  for (const c of new TextEncoder().encode(s)) { h=(h^c)>>>0; h=Math.imul(h,16777619)>>>0; }
  return h>>>0; }
function pcg(v){ v=v>>>0;
  const s=(Math.imul(v,747796405)+2891336453)>>>0;
  const w=Math.imul(((s>>>((s>>>28)+4))^s)>>>0, 277803737)>>>0;
  return ((w>>>22)^w)>>>0; }

function waveTable(name){
  const out=[], h0=fnv1a(name);
  for(let i=0;i<P.waves;i++){
    const h=pcg((h0 ^ (Math.imul(i,2654435761)>>>0))>>>0);
    out.push({ fx:((h & 0xff)/255-0.5)*0.55, fy:(((h>>>8)&0xff)/255-0.5)*0.55,
               ph:((h>>>16)&0xffff)/65535*6.2831853, amp:0.35+((h>>>28)&0xf)/15*0.9 });
  }
  return out;
}
function fieldAt(tab,x,y){ let f=0; for(const c of tab) f += c.amp*Math.cos(c.fx*x + c.fy*y + c.ph);
  return f/tab.length; }

// ---- three.js does the rendering ---------------------------------------------------------------
const renderer = new THREE.WebGLRenderer({canvas:cv, antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.setSize(1160, 652, false);
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.1;
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFShadowMap;

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x060810);
scene.fog = new THREE.Fog(0x060810, 90, 260);
const camera = new THREE.PerspectiveCamera(42, 1160/652, 0.5, 600);
scene.add(new THREE.AmbientLight(0x2a3550, 1.2));
const key = new THREE.DirectionalLight(0xffe9d0, 2.6);
key.position.set(-60, 90, 50); key.castShadow = true;
key.shadow.mapSize.set(2048,2048);
key.shadow.camera.left=-140; key.shadow.camera.right=140;
key.shadow.camera.top=140;  key.shadow.camera.bottom=-140;
key.shadow.camera.near=1;   key.shadow.camera.far=340;
scene.add(key);
const fill = new THREE.DirectionalLight(0x5b86d6, 1.5);
fill.position.set(70, 30, -60); scene.add(fill);

const ground = new THREE.Mesh(new THREE.PlaneGeometry(600,600),
  new THREE.MeshStandardMaterial({color:0x0a0f1a, roughness:0.95, metalness:0.0}));
ground.rotation.x = -Math.PI/2; ground.receiveShadow = true; scene.add(ground);

__GEN__

// ---- the GPU generation pass -------------------------------------------------------------------
const NW = Math.ceil(Math.sqrt(P.towers)), NH = Math.ceil(P.towers / NW);
const genTarget = new THREE.WebGLRenderTarget(NW, NH, {
  type: THREE.FloatType, format: THREE.RGBAFormat, count: 3,
  minFilter: THREE.NearestFilter, magFilter: THREE.NearestFilter, depthBuffer: false });
const genScene = new THREE.Scene();
const genCam = new THREE.OrthographicCamera(-1,1,1,-1,0,1);
const genMat = new THREE.RawShaderMaterial({
  glslVersion: THREE.GLSL3,
  uniforms: { uN:{value:P.towers}, uW:{value:NW}, uNW:{value:P.waves},
              uSeed:{value:0}, uWaves:{value: Array.from({length:P.waves},()=>new THREE.Vector4())} },
  vertexShader: `// LECORE_GEN_VS
precision highp float;
in vec3 position;
void main(){ gl_Position = vec4(position.xy, 0.0, 1.0); }`,
  fragmentShader: GEN_FS,
  depthTest:false, depthWrite:false });
genScene.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2), genMat));

// ONE base geometry, one material, and NO per-instance data on the CPU. The vertex shader builds
// each tower's transform by reading the textures the generator wrote.
const base = new THREE.BoxGeometry(1,1,1);
// The instance transform is read from the generated textures IN THE VERTEX SHADER. Note the order:
// three runs <beginnormal_vertex> BEFORE <begin_vertex>, so the fetch has to live in the normal
// block and the position block reuses it. Declaring it in the position block is a compile error,
// which is exactly what the first version of this did.
function patchVertex(sh, withColor){
  sh.uniforms.uXform = { value: genTarget.textures[0] };
  sh.uniforms.uScl   = { value: genTarget.textures[1] };
  sh.uniforms.uCol   = { value: genTarget.textures[2] };
  sh.uniforms.uGW    = { value: NW };
  sh.vertexShader = `
    uniform sampler2D uXform, uScl, uCol; uniform int uGW;
    ${withColor ? "varying vec3 vTowerColor;" : ""}
    // EVERY INJECTED BLOCK FETCHES FOR ITSELF. three does not guarantee that two chunks both
    // compile: depth_vert wraps <beginnormal_vertex> in #ifdef USE_DISPLACEMENTMAP, so a value
    // declared there simply does not exist in the shadow pass. Two texelFetches instead of one is
    // a rounding error; a block that only works when its neighbour happened to compile is a trap.
    ivec2 lcCell(){ return ivec2(gl_InstanceID % uGW, gl_InstanceID / uGW); }
  ` + sh.vertexShader
      .replace("#include <beginnormal_vertex>", `
    vec3 objectNormal;
    {
      vec4 xf = texelFetch(uXform, lcCell(), 0);
      float c = cos(xf.w), s = sin(xf.w);
      objectNormal = normalize(vec3(c*normal.x + s*normal.z, normal.y, -s*normal.x + c*normal.z));
    }
  `)
      .replace("#include <begin_vertex>", `
    vec3 transformed;
    {
      vec4 xf = texelFetch(uXform, lcCell(), 0);
      vec4 sc = texelFetch(uScl,   lcCell(), 0);
      ${withColor ? "vTowerColor = texelFetch(uCol, lcCell(), 0).rgb;" : ""}
      float c = cos(xf.w), s = sin(xf.w);
      vec3 p = position * sc.xyz;
      transformed = vec3(c*p.x + s*p.z, p.y, -s*p.x + c*p.z) + xf.xyz;
    }
  `);
}

const mat = new THREE.MeshStandardMaterial({roughness:0.62, metalness:0.18});
mat.onBeforeCompile = (sh)=>{
  patchVertex(sh, true);
  mat.userData.sh = sh;
  sh.fragmentShader = "varying vec3 vTowerColor;\n" + sh.fragmentShader.replace(
    "#include <color_fragment>", "#include <color_fragment>\n  diffuseColor.rgb *= vTowerColor;");
};

// SHADOWS GO THROUGH A DIFFERENT MATERIAL. castShadow renders with MeshDepthMaterial, which never
// sees the patch above -- without this every shadow is cast by an untransformed box at the origin.
const depthMat = new THREE.MeshDepthMaterial({ depthPacking: THREE.RGBADepthPacking });
depthMat.onBeforeCompile = (sh)=>{ patchVertex(sh, false); depthMat.userData.sh = sh; };

const city = new THREE.InstancedMesh(base, mat, P.towers);
city.instanceMatrix.setUsage(THREE.StaticDrawUsage);
{ // identity matrices: the real transform lives in the shader, so these are never touched again
  const id = new THREE.Matrix4();
  for(let i=0;i<P.towers;i++) city.setMatrixAt(i, id);
  city.instanceMatrix.needsUpdate = true;
}
city.customDepthMaterial = depthMat;
city.castShadow = true; city.receiveShadow = true;
city.frustumCulled = false;
scene.add(city);

// the field view: the same plane-wave sum drawn as a surface, so the structure behind the skyline
// is visible rather than asserted
const fieldGeo = new THREE.PlaneGeometry(220, 220, 220, 220);
const fieldMat = new THREE.MeshStandardMaterial({color:0x2d4f8c, roughness:0.85, metalness:0.05,
  side:THREE.DoubleSide, wireframe:false});
const field = new THREE.Mesh(fieldGeo, fieldMat);
field.rotation.x = -Math.PI/2; field.receiveShadow = true; field.visible = false;
scene.add(field);

const dummy = new THREE.Object3D();
const col = new THREE.Color();
let table = null, built = 0;

// ---- generation: GPU (leCore) and CPU (the vanilla path), both producing the same scene --------
function setWaves(name){
  const tab = waveTable(name);
  genMat.uniforms.uSeed.value = fnv1a(name) >>> 0;
  for(let i=0;i<P.waves;i++)
    genMat.uniforms.uWaves.value[i].set(tab[i].fx, tab[i].fy, tab[i].ph, tab[i].amp);
  return tab;
}

// leCORE ARM: one fragment per instance, on the GPU, nothing read back.
function generateGPU(name){
  setWaves(name);
  const prev = renderer.getRenderTarget();
  renderer.setRenderTarget(genTarget);
  renderer.render(genScene, genCam);
  renderer.setRenderTarget(prev);
}

// VANILLA ARM: the CPU decode a glTF loader performs, per instance.
function decodeCPU(buf, sink){
  const n = P.towers, F = 13, d = new THREE.Object3D();
  for(let i=0;i<n;i++){
    const o = i*F;
    d.position.set(buf[o], buf[o+1], buf[o+2]);
    d.quaternion.set(buf[o+3], buf[o+4], buf[o+5], buf[o+6]);
    d.scale.set(buf[o+7], buf[o+8], buf[o+9]);
    d.updateMatrix();
    if (sink) sink.set(d.matrix.elements, i*16);
  }
}

// Read the generated instance data back ONCE, only to build the comparison buffer and to prove the
// two arms agree. The demo itself never does this -- the vertex shader reads the textures directly.
function readGenerated(){
  const n = P.towers, out = { xf:new Float32Array(NW*NH*4), sc:new Float32Array(NW*NH*4) };
  renderer.readRenderTargetPixels(genTarget, 0, 0, NW, NH, out.xf, 0);
  renderer.readRenderTargetPixels(genTarget, 0, 0, NW, NH, out.sc, 1);
  return out;
}

function build(name){
  const t0 = performance.now();
  table = setWaves(name);
  generateGPU(name);
  const pos = fieldGeo.attributes.position;
  for(let i=0;i<pos.count;i++) pos.setZ(i, fieldAt(table, pos.getX(i), -pos.getY(i)) * 14);
  pos.needsUpdate = true; fieldGeo.computeVertexNormals();
  built = performance.now() - t0;
  accounting(name);
}

// ---- HEAD TO HEAD AGAINST VANILLA THREE.JS ------------------------------------------------------
// Both arms produce the SAME SCENE and the harness proves it before reporting anything. A
// comparison whose arms disagree is two different programs being timed.
function benchmark(name){
  const n = P.towers, F = 13;
  generateGPU(name);
  const g = readGenerated();
  // the buffer a glTF with EXT_mesh_gpu_instancing would carry, built from the generated scene
  const buf = new Float32Array(n*F);
  const q = new THREE.Quaternion(), e = new THREE.Euler();
  for(let i=0;i<n;i++){
    const o=i*F, t=i*4;
    e.set(0, g.xf[t+3], 0); q.setFromEuler(e);
    buf[o]=g.xf[t]; buf[o+1]=g.xf[t+1]; buf[o+2]=g.xf[t+2];
    buf[o+3]=q.x; buf[o+4]=q.y; buf[o+5]=q.z; buf[o+6]=q.w;
    buf[o+7]=g.sc[t]; buf[o+8]=g.sc[t+1]; buf[o+9]=g.sc[t+2];
  }
  // vanilla: decode on the CPU, three passes, median-ish by averaging
  const outA = new Float32Array(n*16);
  const a0 = performance.now();
  for(let r=0;r<3;r++) decodeCPU(buf, r===2 ? outA : null);
  const tA = (performance.now()-a0)/3;
  // leCore: regenerate on the GPU. finish() so the timer measures the work, not the queue.
  const b0 = performance.now();
  for(let r=0;r<3;r++) generateGPU(name);
  renderer.getContext().finish();
  const tB = (performance.now()-b0)/3;
  // do the arms agree? compare the GPU's transforms against the CPU's decode of the same buffer
  const g2 = readGenerated();
  let worst = 0;
  for(let i=0;i<n;i++){
    const o=i*F, t=i*4;
    worst = Math.max(worst, Math.abs(g2.xf[t]-buf[o]), Math.abs(g2.xf[t+1]-buf[o+1]),
                            Math.abs(g2.xf[t+2]-buf[o+2]), Math.abs(g2.sc[t+1]-buf[o+8]));
  }
  return { n, tA, tB, bytesA: buf.byteLength,
           bytesB: new TextEncoder().encode(name).length, worst };
}

function row(label, vanilla, lecore, cls){
  return `<tr><td>${label}</td><td class="v">${vanilla}</td><td class="v ${cls||''}">${lecore}</td></tr>`;
}
function accounting(name){
  const b = benchmark(name);
  const agree = b.worst < 1e-4;
  const xfer = (mbps, bytes) => (bytes*8/1e6)/mbps*1000;
  const speed = b.tB <= b.tA ? `<span class=ok>${(b.tA/b.tB).toFixed(1)}× faster</span>`
                             : `<span class=bad>${(b.tB/b.tA).toFixed(1)}× slower</span>`;
  document.getElementById("acct").innerHTML = `
   <tr><th></th><th>vanilla three.js</th><th>leCore GLSL</th></tr>
   ${row("scene produced", "reference", agree ? "<span class=ok>IDENTICAL</span> (max |diff| "+b.worst.toExponential(1)+")"
                                              : "<span class=bad>DIFFERENT — ignore the rest</span>")}
   ${row("instances", b.n.toLocaleString(), b.n.toLocaleString())}
   ${row("where the scene comes from", "a downloaded glTF buffer", "a fragment shader, from the name")}
   ${row("scene data downloaded", "<span class=big>"+(b.bytesA/1e6).toFixed(2)+" MB</span>",
         "<span class=big>"+b.bytesB+" bytes</span>")}
   ${row("build the instances", b.tA.toFixed(1)+" ms <span style='color:#69707f'>(CPU decode)</span>",
         b.tB.toFixed(2)+" ms <span style='color:#69707f'>(GPU pass)</span> — "+speed)}
   ${row("read back to the CPU", "every instance", "<span class=ok>nothing</span>")}
   <tr><td colspan=3 style="color:#69707f;padding-top:6px">transfer time from the byte counts &mdash; arithmetic, not measured</td></tr>
   ${row("&nbsp;&nbsp;at 25 Mbps", xfer(25,b.bytesA).toFixed(0)+" ms", xfer(25,b.bytesB).toFixed(2)+" ms")}
   ${row("&nbsp;&nbsp;at 5 Mbps (mobile)", xfer(5,b.bytesA).toFixed(0)+" ms", xfer(5,b.bytesB).toFixed(2)+" ms")}
   ${row("rebuilt into the scene", "&mdash;", built.toFixed(0)+" ms")}`;
}

// ---- the page proves its hash is the engine's --------------------------------------------------
function selfCheck(){
  const msgs = [];
  let worstName = null, bad = 0, checked = 0;
  for(const n of P.names){
    const r = P.refs[n];
    if (fnv1a(n) !== r.fnv) { bad++; worstName = n; continue; }
    for(let i=0;i<r.pcg.length;i++){
      checked++;
      if (pcg((r.fnv ^ i)>>>0) !== r.pcg[i]) { bad++; worstName = n; break; }
    }
  }
  msgs.push(bad === 0
    ? `<span class=ok>this browser computes the engine's hash</span> (${P.names.length} names, ${checked} expansions, exact)`
    : `<span class=bad>HASH MISMATCH on "${worstName}" — this page is generating a different world</span>`);
  // and that the field is actually structured rather than noise: a coherent field has far lower
  // variance between neighbours than white noise does
  const t = waveTable(P.names[0]);
  let dNeighbour = 0, dRandom = 0;
  for(let i=0;i<400;i++){
    const x=(i%20)*8-80, z=Math.floor(i/20)*8-80;
    dNeighbour += Math.abs(fieldAt(t,x,z) - fieldAt(t,x+1,z));
    dRandom    += Math.abs(fieldAt(t,x,z) - fieldAt(t,(i*37)%160-80,(i*91)%160-80));
  }
  const ratio = dRandom/Math.max(dNeighbour,1e-9);
  msgs.push(ratio > 3
    ? `<span class=ok>the field is coherent, not noise</span> (neighbours differ ${ratio.toFixed(1)}× less than distant points)`
    : `<span class=bad>the field is behaving like noise</span> (ratio ${ratio.toFixed(1)})`);
  chk.innerHTML = msgs.join(" · ");
}

// ---- interaction --------------------------------------------------------------------------------
let spin = true, ang = 0.6, dragging = false, lastX = 0, dist = 190, elev = 0.42;
cv.addEventListener("pointerdown", e=>{ dragging=true; lastX=e.clientX; cv.setPointerCapture(e.pointerId); });
cv.addEventListener("pointerup", ()=>{ dragging=false; });
cv.addEventListener("pointermove", e=>{ if(dragging){ ang -= (e.clientX-lastX)*0.005; lastX=e.clientX; } });
cv.addEventListener("wheel", e=>{ dist = Math.min(420, Math.max(70, dist + e.deltaY*0.12)); e.preventDefault(); }, {passive:false});
document.getElementById("go").onclick = ()=> build(document.getElementById("nm").value || "unnamed");
document.getElementById("nm").addEventListener("keydown", e=>{ if(e.key==="Enter") document.getElementById("go").click(); });
document.getElementById("spin").onclick = e=>{ spin=!spin; e.target.textContent="orbit: "+(spin?"on":"off"); };
{
  const box = document.getElementById("viewseg");
  box.addEventListener("click", ev=>{
    const b = ev.target.closest("button"); if(!b) return;
    for(const x of box.querySelectorAll("button")) x.classList.toggle("on", x===b);
    const v = +b.dataset.view;
    city.visible = (v===0); field.visible = (v===1); ground.visible = (v===0);
  });
}

let frames=0, t0=performance.now();
function loop(now){
  if(spin && !dragging) ang += 0.0016;
  camera.position.set(Math.cos(ang)*dist, dist*elev, Math.sin(ang)*dist);
  camera.lookAt(0, 8, 0);
  renderer.render(scene, camera);
  frames++;
  if(now-t0>500){
    const fps = frames*1000/(now-t0); frames=0; t0=now;
    st.innerHTML = `<b>${fps.toFixed(0)} fps</b> · ${P.towers.toLocaleString()} towers, `+
      `${P.waves} plane waves · 1 base geometry, 1 material · `+
      `<b>0 bytes</b> of geometry, texture or placement data downloaded`;
  }
  requestAnimationFrame(loop);
}
build(document.getElementById("nm").value);
selfCheck();
requestAnimationFrame(loop);
</script>
"""

if __name__ == "__main__":
    main()
