#!/usr/bin/env python3
"""Generate liblecore's reproducible single-header/single-source distribution."""

from __future__ import annotations

import argparse
import difflib
import hashlib
import os
from pathlib import Path
import re
import sys
import tempfile


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
NATIVE_ROOT = Path("native/liblecore")
OUTPUT_HEADER = NATIVE_ROOT / "amalgamation/lecore.h"
OUTPUT_SOURCE = NATIVE_ROOT / "amalgamation/lecore.c"

PUBLIC_CORE_HEADER = NATIVE_ROOT / "include/lecore/lecore.h"
PUBLIC_FORMAT_HEADER = NATIVE_ROOT / "include/lecore/lecore_format.h"
CORE_INTERNAL_HEADER = NATIVE_ROOT / "src/internal/lecore_internal.h"
FORMAT_INTERNAL_HEADER = NATIVE_ROOT / "src/internal/format_internal.h"

CORE_SOURCES = (
    NATIVE_ROOT / "src/context.c",
    NATIVE_ROOT / "src/status.c",
    NATIVE_ROOT / "src/vector_f32.c",
    NATIVE_ROOT / "src/vector_f64.c",
    NATIVE_ROOT / "src/cleanup_f32.c",
    NATIVE_ROOT / "src/cleanup_f64.c",
    NATIVE_ROOT / "src/hrr_direct_f32.c",
    NATIVE_ROOT / "src/hrr_direct_f64.c",
    NATIVE_ROOT / "src/hrr_radix2_f32.c",
    NATIVE_ROOT / "src/hrr_radix2_f64.c",
)
FORMAT_SOURCES = (
    NATIVE_ROOT / "src/crc64.c",
    NATIVE_ROOT / "src/format.c",
)
METADATA_INPUTS = (
    Path("LICENSE"),
    NATIVE_ROOT / "VERSION",
    NATIVE_ROOT / "ISA_VERSION",
    NATIVE_ROOT / "PROVENANCE.md",
)
CANONICAL_INPUTS = (
    *METADATA_INPUTS,
    PUBLIC_CORE_HEADER,
    PUBLIC_FORMAT_HEADER,
    CORE_INTERNAL_HEADER,
    FORMAT_INTERNAL_HEADER,
    *CORE_SOURCES,
    *FORMAT_SOURCES,
)

LOCAL_INCLUDE_TARGETS = {
    "lecore/lecore.h",
    "lecore/lecore_format.h",
    "internal/lecore_internal.h",
    "internal/format_internal.h",
}
INCLUDE_RE = re.compile(
    r"^\s*#\s*include\s*([<\"])([^>\"]+)[>\"]\s*(?://.*)?$"
)


def normalized_text(path: Path) -> str:
    """Read UTF-8 source with platform-independent newlines."""

    text = (REPOSITORY_ROOT / path).read_text(encoding="utf-8")
    return text.replace("\r\n", "\n").replace("\r", "\n")


def canonical_digest() -> str:
    digest = hashlib.sha256()
    for path in CANONICAL_INPUTS:
        digest.update(path.as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(normalized_text(path).encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def strip_local_includes(path: Path) -> str:
    """Remove only known includes whose content is embedded in the artifact."""

    output: list[str] = []
    for line_number, line in enumerate(normalized_text(path).splitlines(), 1):
        match = INCLUDE_RE.match(line)
        if match is None:
            output.append(line)
            continue

        delimiter, target = match.groups()
        if target in LOCAL_INCLUDE_TARGETS:
            # Preserve the original line number for the surrounding #line map.
            output.append("")
            continue
        if delimiter == '"' or target.startswith("lecore/"):
            raise RuntimeError(
                f"unexpected local include {target!r} in {path}:{line_number}; "
                "teach the generator how to embed it before regenerating"
            )
        output.append(line)
    return "\n".join(output).rstrip() + "\n"


def license_notice(version: str, isa_version: str, digest: str) -> str:
    listed_inputs = "\n".join(
        f" *   - {path.as_posix()}" for path in CANONICAL_INPUTS
    )
    license_lines = "\n".join(
        f" * {line}" if line else " *"
        for line in normalized_text(Path("LICENSE")).strip().splitlines()
    )
    return f"""/*
 * SPDX-License-Identifier: MIT
 *
 * liblecore {version} amalgamation (ABI 0, ISA {isa_version})
 * Generated by tools/generate_liblecore_amalgamation.py; DO NOT EDIT.
 * Canonical-source SHA-256: {digest}
 *
 * This is a mechanical distribution of the clean-room canonical sources.
 * Provenance details live in native/liblecore/PROVENANCE.md.
 * Generated from:
{listed_inputs}
 *
{license_lines}
 */
"""


def fragment(path: Path) -> str:
    return (
        f'\n#line 1 "{path.as_posix()}"\n'
        f"{strip_local_includes(path)}"
    )


def render_header(version: str, isa_version: str, digest: str) -> str:
    notice = license_notice(version, isa_version, digest)
    return (
        notice
        + """
#ifndef LECORE_AMALGAMATION_H
#define LECORE_AMALGAMATION_H

#define LECORE_AMALGAMATION 1
"""
        + f'#define LECORE_AMALGAMATION_SOURCE_SHA256 "{digest}"\n'
        + f"""

#ifndef LECORE_VERSION_STRING_VALUE
#  define LECORE_VERSION_STRING_VALUE "{version}"
#endif
#ifndef LECORE_ISA_VERSION_VALUE
#  define LECORE_ISA_VERSION_VALUE {isa_version}
#endif
#ifndef LECORE_ABI_VERSION_VALUE
#  define LECORE_ABI_VERSION_VALUE 0
#endif
#ifndef LECORE_ENABLE_FORMAT
#  define LECORE_ENABLE_FORMAT 1
#endif
#ifndef LECORE_ENABLE_RADIX2
#  define LECORE_ENABLE_RADIX2 1
#endif
"""
        + fragment(PUBLIC_CORE_HEADER)
        + "\n#if LECORE_ENABLE_FORMAT\n"
        + fragment(PUBLIC_FORMAT_HEADER)
        + "#endif /* LECORE_ENABLE_FORMAT */\n\n"
        + "#endif /* LECORE_AMALGAMATION_H */\n"
    )


def render_source(version: str, isa_version: str, digest: str) -> str:
    output = [
        license_notice(version, isa_version, digest),
        """
#ifndef LECORE_BUILDING_LIBRARY
#  define LECORE_BUILDING_LIBRARY 1
#endif
#include "lecore.h"
""",
        fragment(CORE_INTERNAL_HEADER),
        "\n#if LECORE_ENABLE_FORMAT\n",
        fragment(FORMAT_INTERNAL_HEADER),
        "#endif /* LECORE_ENABLE_FORMAT */\n",
    ]
    output.extend(fragment(path) for path in CORE_SOURCES)
    output.append("\n#if LECORE_ENABLE_FORMAT\n")
    output.extend(fragment(path) for path in FORMAT_SOURCES)
    output.append("#endif /* LECORE_ENABLE_FORMAT */\n")
    return "".join(output)


def atomic_write_if_changed(path: Path, content: str) -> bool:
    destination = REPOSITORY_ROOT / path
    if destination.exists() and destination.read_text(encoding="utf-8") == content:
        destination.chmod(0o644)
        return False

    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary_name = temporary.name
        os.replace(temporary_name, destination)
        destination.chmod(0o644)
    finally:
        if temporary_name is not None and os.path.exists(temporary_name):
            os.unlink(temporary_name)
    return True


def check_output(path: Path, expected: str) -> bool:
    destination = REPOSITORY_ROOT / path
    if not destination.exists():
        print(f"missing generated artifact: {path}", file=sys.stderr)
        return False

    actual = destination.read_text(encoding="utf-8")
    mode_matches = os.name != "posix" or destination.stat().st_mode & 0o777 == 0o644
    if actual == expected and mode_matches:
        return True

    if not mode_matches:
        actual_mode = destination.stat().st_mode & 0o777
        print(
            f"generated artifact has mode {actual_mode:04o}, expected 0644: {path}",
            file=sys.stderr,
        )
        if actual == expected:
            return False

    print(f"generated artifact is stale: {path}", file=sys.stderr)
    difference = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=f"{path} (checked in)",
        tofile=f"{path} (regenerated)",
        lineterm="",
    )
    for line_number, line in enumerate(difference):
        if line_number == 200:
            print("... diff truncated ...", file=sys.stderr)
            break
        print(line, file=sys.stderr)
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if checked-in amalgamation files differ from canonical inputs",
    )
    arguments = parser.parse_args(argv)

    version = normalized_text(NATIVE_ROOT / "VERSION").strip()
    isa_version = normalized_text(NATIVE_ROOT / "ISA_VERSION").strip()
    if re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", version) is None:
        raise RuntimeError(f"invalid native version: {version!r}")
    if not isa_version.isdecimal():
        raise RuntimeError(f"invalid ISA version: {isa_version!r}")

    digest = canonical_digest()
    expected = {
        OUTPUT_HEADER: render_header(version, isa_version, digest),
        OUTPUT_SOURCE: render_source(version, isa_version, digest),
    }

    if arguments.check:
        return 0 if all(check_output(path, content) for path, content in expected.items()) else 1

    for path, content in expected.items():
        changed = atomic_write_if_changed(path, content)
        print(f"{'generated' if changed else 'unchanged'} {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
