#!/usr/bin/env python3
# tools/new_demo.py -- stamp out a working gallery demo skeleton.
#
# WHERE THIS BELONGS: the demo gallery bundle (it writes demo folders the gallery loads). It lives in tools/
# here with the rest of the build-ergonomics tooling.
#
# WHY THIS EXISTS. Every gallery demo is the same three files under fixed, entirely-tribal conventions:
#   * backend.py  -- must expose a Flask Blueprint literally named `bp`, with a /api/draft endpoint.
#   * index.html  -- the viewport plus a control (a slider), matching the gallery's structure.
#   * demo.json   -- {name, order, category} so the gallery can list it.
# A new demo has been copy-paste-and-rename from an existing one. This generator writes a skeleton that already
# LOADS in the gallery and renders a placeholder, so you start from "it runs" instead of "assemble the
# boilerplate". Then you replace the placeholder render with your actual feature.
#
#   Run it:   python tools/new_demo.py 09_myfeature
#             python tools/new_demo.py 09_myfeature --order 9 --category rendering --dir path/to/gallery

import argparse
import json
import os


# ----------------------------------------------------------------------------------------------------------
# The three file templates. `{name}` etc. are filled in by str.format. Kept readable -- a new contributor
# should be able to open a generated demo and see exactly what each file is for.
# ----------------------------------------------------------------------------------------------------------

BACKEND_TEMPLATE = '''# {name}/backend.py -- generated by tools/new_demo.py. Replace the placeholder render with your feature.
#
# The gallery loads this by importing the module and mounting the Blueprint named `bp` (that name is the
# convention -- keep it). The /api/draft endpoint returns a PNG the viewport shows.

import numpy as np
from flask import Blueprint, request

# demo_kit lives at the gallery root; it wraps the engine's PNG encoder + no-cache headers (see tools/demo_kit).
from demo_kit import png_response, json_response

bp = Blueprint("{name}", __name__)


def _render(t=0.5):
    """PLACEHOLDER: a simple gradient so the demo renders something the moment it is generated. Replace this
    with a call into the engine (e.g. lecore.render.path_trace(...) on your scene). `t` is the slider value."""
    h = w = 128
    ys = np.linspace(0.0, 1.0, h)[:, None]
    xs = np.linspace(0.0, 1.0, w)[None, :]
    img = np.zeros((h, w, 3), float)
    img[..., 0] = xs                       # red ramps left->right
    img[..., 1] = ys                       # green ramps top->bottom
    img[..., 2] = float(t)                 # blue follows the slider, so you can see it working
    return img


@bp.route("/api/draft")
def draft():
    """Return the current frame as a PNG. `t` is the slider value in [0,1] (fast preview compression)."""
    t = float(request.args.get("t", 0.5))
    return png_response(_render(t), level=1)


@bp.route("/api/info")
def info():
    """A tiny JSON endpoint the front end can poll for demo metadata."""
    return json_response({{"name": "{name}", "ready": True}})
'''


INDEX_TEMPLATE = '''<!doctype html>
<!-- {name}/index.html -- generated by tools/new_demo.py. The viewport shows /api/draft; the slider re-fetches. -->
<html>
<head>
  <meta charset="utf-8">
  <title>{name}</title>
  <style>
    body {{ font-family: sans-serif; margin: 1.5rem; }}
    #view {{ image-rendering: pixelated; width: 384px; height: 384px; border: 1px solid #ccc; }}
    .row {{ margin-top: 1rem; }}
  </style>
</head>
<body>
  <h2>{name}</h2>
  <img id="view" src="./api/draft?t=0.5" alt="viewport">
  <div class="row">
    <label>slider <input id="t" type="range" min="0" max="1" step="0.01" value="0.5"></label>
  </div>
  <script>
    // Re-fetch the frame whenever the slider moves. The cache-buster (Date.now) plus the backend's no-cache
    // header guarantees the browser shows the fresh render, not a stale one.
    const view = document.getElementById("view");
    const t = document.getElementById("t");
    t.addEventListener("input", () => {{
      view.src = "./api/draft?t=" + t.value + "&_=" + Date.now();
    }});
  </script>
</body>
</html>
'''


def make_demo(name, base_dir=".", order=0, category="misc"):
    """Create <base_dir>/<name>/ with backend.py, index.html, demo.json. Returns the demo directory path.
    Refuses to overwrite an existing folder (so you never clobber a real demo by re-running the generator)."""
    demo_dir = os.path.join(base_dir, name)
    if os.path.exists(demo_dir):
        raise FileExistsError("%r already exists -- not overwriting" % demo_dir)
    os.makedirs(demo_dir)

    with open(os.path.join(demo_dir, "backend.py"), "w") as f:
        f.write(BACKEND_TEMPLATE.format(name=name))
    with open(os.path.join(demo_dir, "index.html"), "w") as f:
        f.write(INDEX_TEMPLATE.format(name=name))
    with open(os.path.join(demo_dir, "demo.json"), "w") as f:
        json.dump({"name": name, "order": order, "category": category}, f, indent=2)
        f.write("\n")
    return demo_dir


def main(argv=None):
    p = argparse.ArgumentParser(description="Stamp out a working gallery demo skeleton.")
    p.add_argument("name", help="demo folder name, e.g. 09_myfeature")
    p.add_argument("--dir", default=".", help="where to create the demo folder (default: current directory)")
    p.add_argument("--order", type=int, default=0, help="sort order in the gallery")
    p.add_argument("--category", default="misc", help="gallery category")
    args = p.parse_args(argv)
    demo_dir = make_demo(args.name, base_dir=args.dir, order=args.order, category=args.category)
    print("created %s (backend.py, index.html, demo.json) -- it already renders a placeholder." % demo_dir)
    print("next: replace _render() in backend.py with your feature.")


def _selftest():
    """Generate a demo into a temp dir and smoke-test it end to end: the generated backend imports cleanly,
    exposes `bp`, and its /api/draft returns valid PNG. This is the generator proving that what it stamps out
    actually RUNS, which is the whole point."""
    import tempfile, sys, shutil

    d = tempfile.mkdtemp()
    demo_dir = make_demo("09_selftest", base_dir=d, order=9, category="test")
    assert os.path.exists(os.path.join(demo_dir, "backend.py"))
    assert os.path.exists(os.path.join(demo_dir, "index.html"))
    assert json.load(open(os.path.join(demo_dir, "demo.json")))["name"] == "09_selftest"

    # Reproduce the gallery layout: demo_kit sits at the root the demos import from. Copy it next to the demo
    # and put that dir on sys.path, so the generated backend's `from demo_kit import ...` resolves exactly as
    # it would in the real gallery. Then use that same demo_kit to smoke-test the generated demo.
    shutil.copy(os.path.join(os.path.dirname(__file__), "demo_kit.py"), os.path.join(d, "demo_kit.py"))
    # the engine (holographic_render, imported by png_response) lives one level up from tools/ -- in the real
    # gallery it is already on the path; here we add it so the selftest mirrors that environment.
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    sys.path.insert(0, d)
    import demo_kit                                 # the bare module the generated backend also imports
    rows = demo_kit.smoke_test(demo_dir)
    by_route = {r: (s, n) for r, s, n in rows}
    assert by_route["/api/draft"] == (200, "png-ok"), by_route
    print("tools/new_demo selftest OK")


if __name__ == "__main__":
    import sys
    if len(sys.argv) == 1:
        _selftest()
    else:
        main()
